### ISSUE TITLE
Checar denuevo el autograding

### ISSUE THREAD

**Issue by MCC-Oscar-Urias** [itc-mcc/observer-MCC-Oscar-Urias#2]
@ricardo-quintero  Podria revisar denuevo el autograding, parece que hubo un error que no me permitio actualizar a pesar de que el autograding desde mi git corria adecuadamente.Ya corregi y ahora si actualizo

**Comment by ricardo-quintero** [comment]
Ya quedó listo @MCC-Oscar-Urias ...
